name: 🔧 Refactor Code 
description: Use this format for code refactoring tasks.
title: "🔧 [Refactor] <title>"
labels: ["goal: refactor"]
body:
  - type: input
    attributes:
      label: File Name
      description: "Enter the file that you want to refactor in the codebase."
      placeholder: "For example - component/Cards/Card.tsx"
    validations:
      required: true
  - type: textarea
    id: refactor_description
    attributes:
      label: "Reason for Refactoring the Code"
      description: "Describe the improvements that can be made in the codebase without introducing breaking changes."
    validations:
      required: true
  - type: checkboxes
    id: no-duplicate-issues


    attributes:
      label: "Checklist"
      options:

        - label: "I have checked the existing issues."
          required: true

        - label: "I have read the Contributing Guidelines"
          required: true

        - label: "I have read the Code Of Conduct"
          required: true
        
        - label: "The changes don't break the code"
          required: true
